### ISSUE TITLE
mhi_ac_ctrl_core.loop error: -4

### ISSUE THREAD

**Issue by JunghaJungha** [ginkage/MHI-AC-Ctrl-ESPHome#29]
Hi, I just installed this device, I have no airco readings. 
The Wemos d1 is connected to HA (all diagnostic values are there).

In the esphome log it continuously shows:  mhi_ac_ctrl_core.loop error: -4

Any clue?

Thanks,
Koen

**Comment by zuohaot** [comment]
I also saw mhi_ac_ctrl_core.loop error: -2 and mhi_ac_ctrl_core.loop error: -1 in the log as well.

**Comment by schol478** [comment]
Any updates?

**Comment by extera-nl** [comment]
I have the same error

[00:07:54][W][mhi_ac_ctrl:077]: mhi_ac_ctrl_core.loop error: -4

Would be great is this can be fixed. I have 4 working AC units now, flashed with older version op ESPhome, but can get a new unit connected now.

Let me know if I can test something

**Comment by Koendejongh** [comment]
Hi all,

I fully reassembled the hardware and now it works. No more loop errors!

**Comment by schol478** [comment]
The hardware was the problem for me also!

**Comment by zuohaot** [comment]
> The hardware was the problem for me also!

What was causing problems? All my 7 devices are reporting loop error: -2

**Comment by gabcraftia** [comment]
for me it is solved when i plugged it into my AC. When i powered it via micro usb it was giving me error: -4

**Comment by MrAlfabet** [comment]
I'm getting this error on all 3 of my devices. Anyone else with the latest version?

**Comment by melmager** [comment]
mhi_ac_ctrl_core.loop error: -4 - was for me missing clk connection ; Hardware: D1 Mini and own PCB
now loop error -1 , But on / off AC works 
I think -1 is Timing Problem -

**Comment by RobertJansen1** [comment]
Seems like this is hardware related, if there are issues you think can be solved in software please reopen

**Comment by petruknw** [comment]
Is this compatible with the hardware that it was based off https://github.com/absalom-muc/MHI-AC-Ctrl/blob/master/Hardware.md ? Or have I found out the hard way it's not? I'm using the hardware in my link, but even after soldering a second PCB, I still have the same error.
